
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '21.3.0'
        java-version: '21'
        distribution: 'graalvm'
    
    - name: Build native application
      run: ./gradlew build -Dquarkus.package.type=native

    - name: Build Docker image
      run: docker build -f src/main/docker/Dockerfile.native -t ghcr.io/yuki-js/ans-client-demo:1.0.0 .

    - name: Push Docker image
      run: docker push ghcr.io/yuki-js/ans-client-demo:1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -k k8s/overlays/production
